name: Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SLACK_CHANNEL: cicd
      SLACK_COLOR: "#008000"
      SLACK_ICON: http://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
      SLACK_TITLE: Message
      SLACK_USERNAME: GitHub Actions
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_MESSAGE_TEMPLATE: Project `${{ github.repository }}` `${{ github.event_name }}` by `${{ github.actor }}` build


    steps:
      # build
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull submodule
        run: rm -rf public themes/academic && git submodule update --init --recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.71.1"
          extended: true
      - name: Build
        run: hugo


      # deploy
      - name: Build image and publish to docker image registry
        if: ${{ github.repository_owner == 'X-lab2017'}}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: openxlab/xlab-portal:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Update online version
        if: ${{ github.repository_owner == 'X-lab2017'}}
        run: curl ${{ secrets.UPDATE_HOOK }}
      # - name: Push to x-lab2017.github.io
      #   if: ${{ github.repository_owner == 'X-lab2017'}}
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public


      # slack notification
      - name: Slack Notification(Success)
        uses: rtCamp/action-slack-notify@v2.0.0
        if: success() && env.SLACK_WEBHOOK != null
        env:
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE_TEMPLATE}} `success`.
      - name: Slack Notification(Failure)
        uses: rtCamp/action-slack-notify@v2.0.0
        if: failure() && env.SLACK_WEBHOOK != null
        env:
          SLACK_COLOR: "#FF0000"
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE_TEMPLATE}} `failure`.
      - name: Slack Notification(Cancelled)
        uses: rtCamp/action-slack-notify@v2.0.0
        if: cancelled() && env.SLACK_WEBHOOK != null
        env:
          SLACK_COLOR: "#FFFF00"
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE_TEMPLATE}} `cancelled`.
